config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/about", to: "pages#about" 
  resources :tasks  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	private 
	
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
  
  def about    
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: %i[edit show destroy update]

	def new
		@task = Task.new
	end

	def create
		@task = Task.new(params_task)
    @task.user = current_user

    if @task.save!
      redirect_to task_path(@task)
    else
      render :new, status: :unprocessable_entity
    end
	end

	def show
	end

	def index
		@tasks = Task.all
	end

	def edit
	end

	def destroy
		@task.update(params_task)
    redirect_to tasks_path, status: :see_other
	end

	def update
		@task.update(params_task)
    redirect_to task_path(@task)
	end

	private

	def set_task
		@task = Task.find(params[:id])
	end

	def params_task
		params.require(:task).permit(:title, :completed_at, :completed, :support_one, :support_two)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top " id="footer stickyFooter">
    <p class="col-md-4 mb-0 text-muted">&copy; 2022 Company, Inc
    </p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item">
        <a href="#" class="nav-link">How it works</a>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class:"nav-link" %>
      </li>
    </ul>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand"  do %>
      <h4>Kosunga</h4>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in?  %>
          <li class="nav-item active">
            <a class="nav-link" href="#">How it works</a>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class:"nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/jrkinouani" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= current_user.first_name %>
            <%= current_user.last_name %>
              <a class="dropdown-item" href="#">Action</a>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <li class="nav-item active">
            <a class="nav-link" href="#">How it works</a>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
             <%= link_to 'Sign_in',  user_session_path, class:"nav-link" %>
          </li>
        <% end %>
          <li class="nav-item">
            <a href="nav-link"></a>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kosunga</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about page</h1>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container text-center">
    <h1>We never <strong>succeed alone</strong>!</h1>
    <p>Reach your goals in your daily tasks with the support of your loved ones.</p>
    <%= link_to 'Start a new task', new_task_path,  class:"btn btn-primary mt-3"%>
  </div>
</div>

<div class="container mt-5">
  <h1 class="text-center mb-5">How it works</h1>
  <div class="row justify-content-center">
    <div class="col-md-3">
      <i class="fa-solid fa-list-check m-3"></i>
      <h4>1.Create a daily task </h4>
      <p class="explain">Create your daily tasks to learn a language, play sports, lose weight or other challenges you set for yourself. </p>
    </div>
    <div class="col-md-3">
     <i class="fa-solid fa-user-group m-3"></i>
      <h4>2. Invite his supporters </h4>
      <p class="explain">Your loved ones are your first supporters invite them to support you in your challenge.</p>
    </div>
     <div class="col-md-3">
      <i class="fa-solid fa-envelope-circle-check m-3"></i>
       <h4>3. Notifacations </h4>
      <p class="explain">Every day your supporters are alerted by email to support you.</p>
    </div>
    <div class="col-md-3">
      <i class="fa-solid fa-circle-check m-3"></i>
       <h4>4. Success </h4>
      <p class="explain">Your success is assured thanks to your determination and the support of your loved ones. </p>
    </div>
  </div>
</div>

<div class="container text-center mt-5">
   <a class="btn btn-primary mt-3">Start a new task </a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f|%>
  <%= f.input :title,label: 'Nom', placeholder: "Title" %>
  <%= f.input :completed_at, :as => :datetime, placeholder: "Title" %>
  <%= f.input :support_one, placeholder:'My support number one john@doe.com'%>
  <%= f.input :support_two, placeholder:'My support number two justin@doe.com'%>
  <%= f.submit "Valider", class:"btn btn-primary"%>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form',task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <h3 class="text-center mt-3">
    All tasks
  </h3>
  <div class="row justify-content-center">
    <% @tasks.each do |task| %>
     <div class="card col-4 my-2 card_category">
        <div class="card-body" data-turbo="false">
          <h5 class="card-title"><%= link_to task.title, task_path(task)  %></h5>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render 'form',task: @task %>

app/views/tasks/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
  <div class="card-trip mt-5 pb-3">
    <div class="card-trip-infos">
        <h2><%= @task.title%>
    </div>
    <div class="card-trip-infos">
        <h2><%= l(@task.completed_at , format: "%B %Y")%>
    </div>
    <div class="card-trip-infos">
        <h2><%= @task.support_one %>
    </div>
    <div class="card-trip-infos">
        <h2><%= @task.support_two %>
    </div>
   </div>
 </div>
</div>